### ISSUE TITLE
There is a problem with running isaacgym

### ISSUE THREAD

**Issue by laotanlaoban** [PKU-EPIC/GAPartNet#20]
Hello, I encountered an error while trying to run the example code in isaacgym. How can I resolve it?

obj dof: 3 obj links: 4
  0%|                                                                                                                 | 0/1 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 248, in <module>
    for i in range(10): step_num, traj = gym.control_to_pose(
  File "/home/oem/Desktop/GAPartNet/manipulation/object_gym.py", line 1071, in control_to_pose
    self.plan_to_pose_ik(
  File "/home/oem/Desktop/GAPartNet/manipulation/object_gym.py", line 716, in plan_to_pose_ik
    pos_action[:, :7] = self.dof_pos.squeeze(-1)[:, :7] + self.control_ik(dpose)
  File "/home/oem/Desktop/GAPartNet/manipulation/object_gym.py", line 700, in control_ik
    u = (j_eef_T @ torch.inverse(self.j_eef @ j_eef_T + lmbda) @ dpose).view(self.num_envs, 7)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

**Comment by laotanlaoban** [comment]
Additionally, I have filled out the form but could not find where to download the dataset.
